const card=document.querySelector('article.card');const cardKks=document.getElementsByClassName('card-kks')[0];const cardAboutMe=document.querySelector('.card-aboutme')
const btnSee=document.querySelector('.btn-seemore');const btnSee2=document.querySelector('.card-kks .btn-seemore');const btnSee3=document.querySelector('.card-aboutme .btn-seemore')
const btnClose=document.querySelector('.btn-close');const btnClose2=document.getElementsByClassName('btn-close')[1];const btnClose3=document.getElementsByClassName('btn-close')[2];btnSee.addEventListener('click',function(){card.classList.add('animate-see');card.classList.remove('animate-close');btnSee.style.display='none';});btnClose.addEventListener('click',function(){card.classList.add('animate-close');card.classList.remove('animate-see');btnSee.style.display='flex';})
btnSee2.addEventListener('click',function(){cardKks.classList.add('animate-see2')
cardKks.classList.remove('animate-close2')
btnSee2.style.display='none'})
btnClose2.addEventListener('click',function(){cardKks.classList.add('animate-close2')
cardKks.classList.remove('animate-see2')
btnSee2.style.display='flex'})
btnSee3.addEventListener('click',function(){cardAboutMe.classList.add('animate-see3')
cardAboutMe.classList.remove('animate-close3')
btnSee3.style.display='none'})
btnClose3.addEventListener('click',function(){cardAboutMe.classList.add('animate-close3')
cardAboutMe.classList.remove('animate-see3')
btnSee3.style.display='flex'})